---
abstract: 'An event-based Markdown parser toolkit'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  File::Slurp: 0
  Test::Deep: 0
  Test::Differences: 0
  Test::Exception: 0
  Test::More: 0.88
  Tree::Simple::Visitor::ToNestedArray: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 3.101520, CPAN::Meta::Converter version 2.101461'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Markdent
requires:
  Digest::SHA1: 0
  HTML::Stream: 0
  List::AllUtils: 0
  Moose: 0.92
  MooseX::Params::Validate: 0.12
  MooseX::Role::Parameterized: 0
  MooseX::SemiAffordanceAccessor: 0.05
  MooseX::StrictConstructor: 0.08
  MooseX::Types: 0.20
  Tree::Simple: 0
  Try::Tiny: 0
  namespace::autoclean: 0.09
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Markdent
  repository: http://hg.urth.org/hg/Markdent
version: 0.14
