---
abstract: 'An event-based Markdown parser toolkit'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  Data::Dumper: 0
  File::Basename: 0
  File::Find: 0
  File::Temp: 0
  IO::File: 0
  Test::Deep: 0
  Test::Differences: 0
  Test::Fatal: 0
  Test::More: 0.88
  Tree::Simple::Visitor::ToNestedArray: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300016, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Markdent
requires:
  Class::Load: 0
  Digest::SHA1: 0
  Exporter: 0
  File::Slurp: 0
  Getopt::Long: 0
  HTML::Stream: 0
  IO::Handle: 0
  List::AllUtils: 0
  Moose: 0.92
  Moose::Role: 0
  MooseX::Params::Validate: 0
  MooseX::Role::Parameterized: 0
  MooseX::SemiAffordanceAccessor: 0.05
  MooseX::StrictConstructor: 0.08
  MooseX::Types: 0.20
  MooseX::Types::Combine: 0
  MooseX::Types::Moose: 0
  Scalar::Util: 0
  Tree::Simple: 0
  Try::Tiny: 0
  base: 0
  namespace::autoclean: 0.09
  re: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Markdent
  repository: git://git.urth.org/Markdent.git
version: 0.21
