
BEGIN {
  unless ($ENV{AUTHOR_TESTING}) {
    require Test::More;
    Test::More::plan(skip_all => 'these tests are for testing by the author');
  }
}

use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.004003
eval "use Test::Spelling 0.12; use Pod::Wordlist::hanekomu; 1" or die $@;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
API
CLI
CaptureEvents
EndCode
GitHub
Gruber
Gruber's
HTMLStream
MARKDENT
Markdent
Markdent's
Markdown
PayPal
Rolsky
SHAs
StartCode
StartEmphasis
StartLink
XML's
blockquote
blockquotes
colspan
doctype
escapeable
esque
html
inline
mdtest
namespace
parameterized
parser's
parsers
preformatted
unordered
uri
wiki
DROLSKY
DROLSKY's
Rolsky's
Dave
autarch
lib
Event
StartTableCell
EndHTMLTag
Role
Dialect
SpanParser
EndBlockquote
EndListItem
BalancedEvent
EndOrderedList
HTMLEntity
CodeBlock
StartTableHeader
Theory
EndParagraph
Parser
Handler
Fragment
Standard
StartTableRow
EndDocument
BlockParser
CapturedEvents
EndUnorderedList
StartParagraph
StartTableBody
EndLink
FilterHandler
StartStrong
DebugPrinter
LineBreak
EndTableBody
HTMLBlock
Null
Image
StartUnorderedList
EndTableHeader
StartListItem
EndEmphasis
AnyParser
Preformatted
Types
Internal
HTMLTag
EventsAsMethods
HTMLComment
Text
HTMLFilter
StartDocument
EventAsText
StartBlockquote
HTMLCommentBlock
HorizontalRule
Document
Simple
MinimalTree
StartTable
StartHTMLTag
AutoLink
EndTableRow
StartHeader
EndHeader
EndTableCell
Multiplexer
EndTable
EndStrong
Regexes
Manual
StartOrderedList
