
BEGIN {
  unless ($ENV{AUTHOR_TESTING}) {
    require Test::More;
    Test::More::plan(skip_all => 'these tests are for testing by the author');
  }
}

use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006008
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
DROLSKY
DROLSKY's
Rolsky
Rolsky's
API
CLI
CaptureEvents
EndCode
GitHub
Gruber
Gruber's
HTMLStream
MARKDENT
Markdent
Markdent's
Markdown
PayPal
SHAs
StartCode
StartEmphasis
StartLink
XML's
blockquote
blockquotes
colspan
doctype
escapeable
esque
html
inline
lang
mdtest
namespace
parameterized
parser's
parsers
preformatted
unordered
uri
wiki
Dave
autarch
Jason
McIntosh
jmac
lib
CapturedEvents
Dialect
BlockParser
SpanParser
Standard
Theory
Event
AutoLink
CodeBlock
EndBlockquote
EndDocument
EndEmphasis
EndHTMLTag
EndHeader
EndLink
EndListItem
EndOrderedList
EndParagraph
EndStrong
EndTable
EndTableBody
EndTableCell
EndTableHeader
EndTableRow
EndUnorderedList
HTMLBlock
HTMLComment
HTMLCommentBlock
HTMLEntity
HTMLTag
HorizontalRule
Image
LineBreak
Preformatted
StartBlockquote
StartDocument
StartHTMLTag
StartHeader
StartListItem
StartOrderedList
StartParagraph
StartStrong
StartTable
StartTableBody
StartTableCell
StartTableHeader
StartTableRow
StartUnorderedList
Text
Handler
HTMLFilter
Document
Fragment
MinimalTree
Multiplexer
Null
Manual
Parser
Regexes
Role
AnyParser
BalancedEvent
DebugPrinter
EventAsText
EventsAsMethods
FilterHandler
Simple
Types
Internal
